### PR TITLE
Feature/cluster leader

### PR DESCRIPTION
**Pull request by agadek**
Ive added cluster leader info to members resources as I see it quite useful. I case of any objection we can substitute it with extra resource path.

### CODE REVIEW

**Comment by raboof** [comment]
LGTM, seems useful indeed!

**Comment by agadek** [comment]
I'd reale like to use this feature. Is their option to get snapshot jar from some maven jar ?

**Comment by 2m** [comment]
@agadek looks like you pushed some additional commits to this branch. Did you mean to do so?

**Comment by agadek** [comment]
accident reverted ;-)

**Comment by 2m** [comment]
Cool. Thanks. :)

**Pull request merged**
